export const NEW_ALERT = 'NEW_ALERT'
export const CLOSE_ALERTS = 'CLOSE_ALERTS'

// generic async stuff
export const UPDATE_FIREBASE = 'UPDATE_FIREBASE'

// errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const HANDLE_ERRORS = 'HANDLE_ERRORS'

//user
export const CHECK_USER_TOKEN = 'CHECK_USER_TOKEN'
export const CREATE_USER_WITH_EMAIL = 'CREATE_USER_WITH_EMAIL'
export const CURRENT_USER_OUTDATED = 'CURRENT_USER_OUTDATED'
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST'
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_IMAGE = 'SET_IMAGE'
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST'
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

// viewSettings
export const SET_CURRENT_MODAL = 'SET_CURRENT_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SET_VIEW_MODE = 'SET_VIEW_MODE'

//miscellaneous UI
export const HANDLE_QUERY = 'HANDLE_QUERY'
export const SET_PARAMS = 'SET_PARAMS'
export const CLEAR_PARAMS = 'CLEAR_PARAMS'
export const SET_OPTIONS = 'SET_OPTIONS'
export const FORM_PERSISTED = 'FORM_PERSISTED'

